pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Mr-Marshal1/java_framework'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'mvn clean install'
            }
        }

      stage('Run Tests') {
          steps {
               sh 'mvn test -Dtest=APITest.NewAPI'
               sh 'mvn test -Dtest=UITest.GoogleTest'
          }
      }

        stage('Generate Allure Report') {
            steps {
                sh 'wget -O allure-2.14.0.zip https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip'
                sh 'unzip allure-2.14.0.zip'
                sh 'export PATH=$PATH:/path/to/allure-2.14.0/bin'

                sh 'allure generate target/allure-results --clean -o target/allure-report'

                archiveArtifacts artifacts: 'target/allure-results/*'
            }
        }
    }
}